import type { Metadata } from "next";
import "./globals.css";
import Profile from "@/components/Profile";
import Footer from "@/components/Footer";
import { IBM_Plex_Sans_Thai } from "next/font/google";

const inter = IBM_Plex_Sans_Thai({ subsets: ["thai"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={inter.className}
    >
      <body>
        <div className="container place-self-center py-10 px-4 xl:px-0 space-y-6 text-lg">
          <Profile />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
